{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wear-compose-foundation/1.7.1-cmp02/wear-compose-foundation-1.7.1-cmp02.module",
    "group": "ee.schimke.wearcmp",
    "module": "wear-compose-foundation",
    "version": "1.7.1-cmp02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.1-cmp02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-foundation-jvm-1.7.1-cmp02.jar",
          "url": "wear-compose-foundation-jvm-1.7.1-cmp02.jar",
          "size": 947477,
          "sha512": "6ba533f208a016ee8b5f101ec5cb436556e795fd38645c3d8e81dc5945c5a5bea4f6e6e2851d4d98e22f4bc9f753cbed92d9e12d9eca4bbf0e02ba05d8e325e0",
          "sha256": "c3f6a05f862c566d02f02b35da25ce218faa3bdf17d59dfd09debf8294aeabad",
          "sha1": "b59759c40dac5fcf48ce0304dcbf7babd375d9e5",
          "md5": "32f6cb35e340f5edc58e7ac37f023901"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.1-cmp02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-foundation-jvm-1.7.1-cmp02.jar",
          "url": "wear-compose-foundation-jvm-1.7.1-cmp02.jar",
          "size": 947477,
          "sha512": "6ba533f208a016ee8b5f101ec5cb436556e795fd38645c3d8e81dc5945c5a5bea4f6e6e2851d4d98e22f4bc9f753cbed92d9e12d9eca4bbf0e02ba05d8e325e0",
          "sha256": "c3f6a05f862c566d02f02b35da25ce218faa3bdf17d59dfd09debf8294aeabad",
          "sha1": "b59759c40dac5fcf48ce0304dcbf7babd375d9e5",
          "md5": "32f6cb35e340f5edc58e7ac37f023901"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "wear-compose-foundation-jvm-1.7.1-cmp02-sources.jar",
          "url": "wear-compose-foundation-jvm-1.7.1-cmp02-sources.jar",
          "size": 230759,
          "sha512": "ac2f3d9188d618b045152139c0aba52e23c4431410d5a274ceba887d4f79851441e8be420070762ba618946622444dca324f3a4bfa43104c94301df9e1ba1424",
          "sha256": "4c381b9c9f036745a4af250706dff4395fb75f5c86d1ba02aaafffa9b9dd5e98",
          "sha1": "1f51f0419be33216fae6243834a89861ce5f1b2a",
          "md5": "5085152c833f0b2d2b9ec697a3732cf0"
        }
      ]
    }
  ]
}
