{
  "formatVersion": "1.1",
  "component": {
    "url": "../../remote-creation-compose/4307936-ps17-cmp01/remote-creation-compose-4307936-ps17-cmp01.module",
    "group": "ee.schimke.remotecompose",
    "module": "remote-creation-compose",
    "version": "4307936-ps17-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.remote",
          "module": "remote-creation",
          "version": {
            "requires": "1.0.0-alpha19"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-write-core",
          "version": {
            "requires": "4307936-ps17-cmp01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-creation-compose.aar",
          "url": "remote-creation-compose-android-4307936-ps17-cmp01.aar",
          "size": 1593999,
          "sha512": "6051e118a824cdd44a7356c21cde30d702be203bb8f940e6e1c08a89db6422776df03883aa23e84149410cefde70e6e976b026b4d16bd1a9273d816e3da97ae9",
          "sha256": "9cb8c3aec23147db0097154ab4a08e8ce7b7e42a16678b0e494076b10642e2cd",
          "sha1": "0691cdee15d701a22d075a21e568977d2eff0c3d",
          "md5": "70f624d4471ef91bc6257ec70d9c756c"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.remote",
          "module": "remote-creation",
          "version": {
            "requires": "1.0.0-alpha19"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-write-core",
          "version": {
            "requires": "4307936-ps17-cmp01"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-path",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "remote-creation-compose.aar",
          "url": "remote-creation-compose-android-4307936-ps17-cmp01.aar",
          "size": 1593999,
          "sha512": "6051e118a824cdd44a7356c21cde30d702be203bb8f940e6e1c08a89db6422776df03883aa23e84149410cefde70e6e976b026b4d16bd1a9273d816e3da97ae9",
          "sha256": "9cb8c3aec23147db0097154ab4a08e8ce7b7e42a16678b0e494076b10642e2cd",
          "sha1": "0691cdee15d701a22d075a21e568977d2eff0c3d",
          "md5": "70f624d4471ef91bc6257ec70d9c756c"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "remote-creation-compose-android-4307936-ps17-cmp01-sources.jar",
          "url": "remote-creation-compose-android-4307936-ps17-cmp01-sources.jar",
          "size": 380454,
          "sha512": "5b047d07f12a474419812994afa35af0082ec10a413d771f48e874f79969e7b497d1d85399004aa73f5510c84dfa4ba3d13885f8bfe100ad560508df0f95651c",
          "sha256": "3f52b866be8a451cb204e7ab035574fa4589dcdcf1e05e8e7d8e281e1a6785bb",
          "sha1": "428653bc4eaab96b803298e30ae27a1df8290130",
          "md5": "1e9ecea31b5b70888842031ac073f580"
        }
      ]
    }
  ]
}
