{
  "formatVersion": "1.1",
  "component": {
    "url": "../../remote-write-core/4307936-ps17-cmp04/remote-write-core-4307936-ps17-cmp04.module",
    "group": "ee.schimke.remotecompose",
    "module": "remote-write-core",
    "version": "4307936-ps17-cmp04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-write-core-wasm-js-4307936-ps17-cmp04.klib",
          "url": "remote-write-core-wasm-js-4307936-ps17-cmp04.klib",
          "size": 201481,
          "sha512": "5b31c5b0f54a5264293ca5f89658cb79af5f8c0cb8c0205d29bd58d628a97aa9e5feca5ee79637320c3b0d2ea20ca71f9f09224537ccfaff5711f8ac165e6854",
          "sha256": "f00a77d840f7309c019ab26b71db273033377ecac401097328abe0aa154e8614",
          "sha1": "d745c745d29f8e5644b7f162a5f17065eb507a63",
          "md5": "ea56c7322a4b8f682ce8529e47089c08"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-write-core-wasm-js-4307936-ps17-cmp04.klib",
          "url": "remote-write-core-wasm-js-4307936-ps17-cmp04.klib",
          "size": 201481,
          "sha512": "5b31c5b0f54a5264293ca5f89658cb79af5f8c0cb8c0205d29bd58d628a97aa9e5feca5ee79637320c3b0d2ea20ca71f9f09224537ccfaff5711f8ac165e6854",
          "sha256": "f00a77d840f7309c019ab26b71db273033377ecac401097328abe0aa154e8614",
          "sha1": "d745c745d29f8e5644b7f162a5f17065eb507a63",
          "md5": "ea56c7322a4b8f682ce8529e47089c08"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "remote-write-core-wasm-js-4307936-ps17-cmp04-sources.jar",
          "url": "remote-write-core-wasm-js-4307936-ps17-cmp04-sources.jar",
          "size": 24885,
          "sha512": "cc8f82079013a1c6eeb0128fb4001f8bacd0ea4400d806e0d5479c756051ff8b496ea35e42d6a59d5b6b08c050b854f4259534011661cef392cc527fc7ea3f78",
          "sha256": "da6506309f071b57fbd719ca1e56ce390f39d6733404a75c7b1b56e410e0ed5d",
          "sha1": "d88fc854d7c8f4eefa9d49e019bf6965d16092bc",
          "md5": "9ae468b2a152fd26267760933b2c803a"
        }
      ]
    }
  ]
}
