{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wear-compose-fonts/1.7.0-rc01-cmp01/wear-compose-fonts-1.7.0-rc01-cmp01.module",
    "group": "ee.schimke.wearcmp",
    "module": "wear-compose-fonts",
    "version": "1.7.0-rc01-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-fonts-jvm-1.7.0-rc01-cmp01.jar",
          "url": "wear-compose-fonts-jvm-1.7.0-rc01-cmp01.jar",
          "size": 1010259,
          "sha512": "5919a19e6a8f6c3166c19aa4f3e828154c99b600417d7ed26219d96c88b49b99f6fa1c877777c515a385fbcf39b6acc576867a92654d4146c23e5a1a27519f7e",
          "sha256": "c760c2672cc19f7c61460d8cfc1456d3dcdae12e4be7bd221a0d328cfd3b82fa",
          "sha1": "313a4ac76e1c5624d5feb7378e4e25facab2cced",
          "md5": "3d34a499ab4597a4eaf43b3a71d2ecf9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-fonts-jvm-1.7.0-rc01-cmp01.jar",
          "url": "wear-compose-fonts-jvm-1.7.0-rc01-cmp01.jar",
          "size": 1010259,
          "sha512": "5919a19e6a8f6c3166c19aa4f3e828154c99b600417d7ed26219d96c88b49b99f6fa1c877777c515a385fbcf39b6acc576867a92654d4146c23e5a1a27519f7e",
          "sha256": "c760c2672cc19f7c61460d8cfc1456d3dcdae12e4be7bd221a0d328cfd3b82fa",
          "sha1": "313a4ac76e1c5624d5feb7378e4e25facab2cced",
          "md5": "3d34a499ab4597a4eaf43b3a71d2ecf9"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "wear-compose-fonts-jvm-1.7.0-rc01-cmp01-sources.jar",
          "url": "wear-compose-fonts-jvm-1.7.0-rc01-cmp01-sources.jar",
          "size": 2885,
          "sha512": "974198defacd82d283d43f96e49e14abc61eace0a2c5519f40e683b502acaeb47fd7008508840609bc57c39d8bded10266187aa7473a1a69aad834cea4145819",
          "sha256": "5da2cf0ab7a9a4c9ee897e02fcb27b3bffc1ac07ce02e9f0df4f7d46c8b491cb",
          "sha1": "492a155c94925a59fe6a507be28a1abc624e6bec",
          "md5": "6de09c3b57dede9bb6f7ab76c26ecdc8"
        }
      ]
    }
  ]
}
