{
  "formatVersion": "1.1",
  "component": {
    "url": "../../port-runtime/1.7.0-rc01-cmp01/port-runtime-1.7.0-rc01-cmp01.module",
    "group": "ee.schimke.wearcmp",
    "module": "port-runtime",
    "version": "1.7.0-rc01-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "port-runtime-wasm-js-1.7.0-rc01-cmp01.klib",
          "url": "port-runtime-wasm-js-1.7.0-rc01-cmp01.klib",
          "size": 65687,
          "sha512": "8755bc20736d6b9b89db84a7c240b5ea792f81c390d2015115ee6edc72473c960914e76e1012d1eb15eddf448884150520cfa03cf115cfbb3683bab07e721e98",
          "sha256": "14c96458f68e943e2a6cbf22c3b5064b11e50d9691d33a6191e3a6d193bb2ad5",
          "sha1": "80271f0866da859655e3f0e963af8505b9b22df5",
          "md5": "5dc347c1df5ebc2ce88b56440be4c70b"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "port-runtime-wasm-js-1.7.0-rc01-cmp01.klib",
          "url": "port-runtime-wasm-js-1.7.0-rc01-cmp01.klib",
          "size": 65687,
          "sha512": "8755bc20736d6b9b89db84a7c240b5ea792f81c390d2015115ee6edc72473c960914e76e1012d1eb15eddf448884150520cfa03cf115cfbb3683bab07e721e98",
          "sha256": "14c96458f68e943e2a6cbf22c3b5064b11e50d9691d33a6191e3a6d193bb2ad5",
          "sha1": "80271f0866da859655e3f0e963af8505b9b22df5",
          "md5": "5dc347c1df5ebc2ce88b56440be4c70b"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "port-runtime-wasm-js-1.7.0-rc01-cmp01-sources.jar",
          "url": "port-runtime-wasm-js-1.7.0-rc01-cmp01-sources.jar",
          "size": 36706,
          "sha512": "185d1b65a00e4556936e0f9ce29fcee2f267642c34e13d27c7a0ee06233b7fc62373aa9f8eae34a2c301f2054bf56027d7e672ec14d59c51c4f399d73af960db",
          "sha256": "1a10873c7dccda45d15ddc197509476df088c220313afbcdb510a1c28633d356",
          "sha1": "a74608cff33f35ed68767e229d92068a0ae88b07",
          "md5": "5c8035e9bbf2550950083f72e7ea87a6"
        }
      ]
    }
  ]
}
