{
  "formatVersion": "1.1",
  "component": {
    "group": "ee.schimke.remotecompose",
    "module": "remote-creation-compose",
    "version": "4307936-ps17-cmp03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-write-core",
          "version": {
            "requires": "4307936-ps17-cmp03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-creation-compose-metadata-4307936-ps17-cmp03.jar",
          "url": "remote-creation-compose-4307936-ps17-cmp03.jar",
          "size": 152469,
          "sha512": "c2c01e9d6cbc04943c172f64972cb59d81a3ddfdffbe6f139bc8014551d5d210621a14c4053b8270983b880f5117eb2d24b0bd3faa5792bf4b6a6c5a3b0c2c19",
          "sha256": "4300374b2959d73c9d86a70371750f3dcdf805910ebf2eec92839360f62beab6",
          "sha1": "d05b1bc48b8340a60dc227e8688b148399857761",
          "md5": "cccbfe0f9efa82906d4228196a9c221e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "remote-creation-compose-kotlin-4307936-ps17-cmp03-sources.jar",
          "url": "remote-creation-compose-4307936-ps17-cmp03-sources.jar",
          "size": 314022,
          "sha512": "fcbd5344f31b0f5c245edbd52bebb4651111b46b5dcc8ce5bc79994873df0a8ec4350d0108681dda55b1c98f14043ba43d71817416d5784dea6b54c6e18fba34",
          "sha256": "81580aab9420b2b9c2c16ebcc0440cd9266d9a72994eab4f15fcae88fa2487f7",
          "sha1": "cedbd74c2081030014ed594e87dbf262897bc8b3",
          "md5": "1466dac03678a5ebf8540192f10e44b4"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../remote-creation-compose-android/4307936-ps17-cmp03/remote-creation-compose-android-4307936-ps17-cmp03.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-creation-compose-android",
        "version": "4307936-ps17-cmp03"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../remote-creation-compose-android/4307936-ps17-cmp03/remote-creation-compose-android-4307936-ps17-cmp03.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-creation-compose-android",
        "version": "4307936-ps17-cmp03"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../remote-creation-compose-android/4307936-ps17-cmp03/remote-creation-compose-android-4307936-ps17-cmp03.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-creation-compose-android",
        "version": "4307936-ps17-cmp03"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../remote-creation-compose-jvm/4307936-ps17-cmp03/remote-creation-compose-jvm-4307936-ps17-cmp03.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-creation-compose-jvm",
        "version": "4307936-ps17-cmp03"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../remote-creation-compose-jvm/4307936-ps17-cmp03/remote-creation-compose-jvm-4307936-ps17-cmp03.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-creation-compose-jvm",
        "version": "4307936-ps17-cmp03"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../remote-creation-compose-jvm/4307936-ps17-cmp03/remote-creation-compose-jvm-4307936-ps17-cmp03.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-creation-compose-jvm",
        "version": "4307936-ps17-cmp03"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../remote-creation-compose-wasm-js/4307936-ps17-cmp03/remote-creation-compose-wasm-js-4307936-ps17-cmp03.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-creation-compose-wasm-js",
        "version": "4307936-ps17-cmp03"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../remote-creation-compose-wasm-js/4307936-ps17-cmp03/remote-creation-compose-wasm-js-4307936-ps17-cmp03.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-creation-compose-wasm-js",
        "version": "4307936-ps17-cmp03"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../remote-creation-compose-wasm-js/4307936-ps17-cmp03/remote-creation-compose-wasm-js-4307936-ps17-cmp03.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-creation-compose-wasm-js",
        "version": "4307936-ps17-cmp03"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../remote-creation-compose-wasm-js/4307936-ps17-cmp03/remote-creation-compose-wasm-js-4307936-ps17-cmp03.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-creation-compose-wasm-js",
        "version": "4307936-ps17-cmp03"
      }
    }
  ]
}
