{
  "formatVersion": "1.1",
  "component": {
    "url": "../../remote-creation-compose/4307936-ps17-cmp02/remote-creation-compose-4307936-ps17-cmp02.module",
    "group": "ee.schimke.remotecompose",
    "module": "remote-creation-compose",
    "version": "4307936-ps17-cmp02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.remote",
          "module": "remote-creation",
          "version": {
            "requires": "1.0.0-alpha19"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-write-core",
          "version": {
            "requires": "4307936-ps17-cmp02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-creation-compose.aar",
          "url": "remote-creation-compose-android-4307936-ps17-cmp02.aar",
          "size": 1596126,
          "sha512": "37d20dc637af30cdb73c2ae0bdadb1465c5fc33d824e0718909a202206d9e91d8181bb8070f7670705970cdfbdb5f476818b54a84c52708135cdfdf548d2dd0c",
          "sha256": "973e09b3fc0fd4b53b401100684581e679363bdfd08b11edc39b5b8bfddf206f",
          "sha1": "0accea85c727a8acc6f5d367c968d6430f174270",
          "md5": "6f51fba918df96f2aea1e3011452f532"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.remote",
          "module": "remote-creation",
          "version": {
            "requires": "1.0.0-alpha19"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-write-core",
          "version": {
            "requires": "4307936-ps17-cmp02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-path",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "remote-creation-compose.aar",
          "url": "remote-creation-compose-android-4307936-ps17-cmp02.aar",
          "size": 1596126,
          "sha512": "37d20dc637af30cdb73c2ae0bdadb1465c5fc33d824e0718909a202206d9e91d8181bb8070f7670705970cdfbdb5f476818b54a84c52708135cdfdf548d2dd0c",
          "sha256": "973e09b3fc0fd4b53b401100684581e679363bdfd08b11edc39b5b8bfddf206f",
          "sha1": "0accea85c727a8acc6f5d367c968d6430f174270",
          "md5": "6f51fba918df96f2aea1e3011452f532"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "remote-creation-compose-android-4307936-ps17-cmp02-sources.jar",
          "url": "remote-creation-compose-android-4307936-ps17-cmp02-sources.jar",
          "size": 381354,
          "sha512": "62256f3f8af16e2a035bfeb1ea14dc4c9c63564e770510bcc245b4b2d2163bc52b69daa9a74e6cd7fb632530776ef6e9fd2305ef7b56fc8d18a772452c04c789",
          "sha256": "79535ff19308a053a0845970d6246a963d79058f4e31ab9184734ffb10f38487",
          "sha1": "1b5e51e3e394f9819016db80688945d3f61986e7",
          "md5": "0d2dabc7b52df3aa3f33e41eff78dc9c"
        }
      ]
    }
  ]
}
