{
  "formatVersion": "1.1",
  "component": {
    "group": "ee.schimke.wearcmp",
    "module": "wear-compose-fonts",
    "version": "1.7.0-rc01-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-fonts-metadata-1.7.0-rc01-cmp01.jar",
          "url": "wear-compose-fonts-1.7.0-rc01-cmp01.jar",
          "size": 2210,
          "sha512": "47e077b3374e783d649177f6b53059e29a4c838210dfb40335bb31d2de3f84f1e1657dbf4087a2a2f351806a48d49e953f26f59de2c1efd1d7a919064fe833d1",
          "sha256": "f4e12dcc4661dfee86411ec70d2e947eaf085f291fa05d3b85c2060dfa19c78a",
          "sha1": "6ccd5c7ec20d5d5b216ad12449b27c983dc5471c",
          "md5": "8fe65fd3f40e9934aab6a4d379ee0e65"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "wear-compose-fonts-kotlin-1.7.0-rc01-cmp01-sources.jar",
          "url": "wear-compose-fonts-1.7.0-rc01-cmp01-sources.jar",
          "size": 1721,
          "sha512": "5b065833a77510d429d6d3a789d84b24f0337a3d5d73be5ee928863921d297d7e322b0660809081e258243a5fe15ee458d11607cb8c1400611c156ab638eed17",
          "sha256": "dbcc36df4f3e5cf061c7d494b2a00f3a14813bbee3807551566264769986ed9b",
          "sha1": "c3442d26ed6f324ef88b27d202fd89b893244310",
          "md5": "8f4d5de2891b8dba20a67c13fe42563d"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wear-compose-fonts-jvm/1.7.0-rc01-cmp01/wear-compose-fonts-jvm-1.7.0-rc01-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-fonts-jvm",
        "version": "1.7.0-rc01-cmp01"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wear-compose-fonts-jvm/1.7.0-rc01-cmp01/wear-compose-fonts-jvm-1.7.0-rc01-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-fonts-jvm",
        "version": "1.7.0-rc01-cmp01"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wear-compose-fonts-jvm/1.7.0-rc01-cmp01/wear-compose-fonts-jvm-1.7.0-rc01-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-fonts-jvm",
        "version": "1.7.0-rc01-cmp01"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wear-compose-fonts-wasm-js/1.7.0-rc01-cmp01/wear-compose-fonts-wasm-js-1.7.0-rc01-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-fonts-wasm-js",
        "version": "1.7.0-rc01-cmp01"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wear-compose-fonts-wasm-js/1.7.0-rc01-cmp01/wear-compose-fonts-wasm-js-1.7.0-rc01-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-fonts-wasm-js",
        "version": "1.7.0-rc01-cmp01"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wear-compose-fonts-wasm-js/1.7.0-rc01-cmp01/wear-compose-fonts-wasm-js-1.7.0-rc01-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-fonts-wasm-js",
        "version": "1.7.0-rc01-cmp01"
      }
    }
  ]
}
