{
  "formatVersion": "1.1",
  "component": {
    "group": "ee.schimke.remotecompose",
    "module": "remote-write-core",
    "version": "4307936-ps17-cmp03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-write-core-metadata-4307936-ps17-cmp03.jar",
          "url": "remote-write-core-4307936-ps17-cmp03.jar",
          "size": 24616,
          "sha512": "bf6572363528641c45628b8aa83205cf8e3a15797a4b692ca3b6014beaf13cefd601d683856a628d9d5d3b525d2d169ee8598a86efdb531a0e3a53aed2beb569",
          "sha256": "fcee37a585d969c73ce7f86b7781afd53c90f5c8f6c723228ce6dfa2952bb385",
          "sha1": "e1156b656e4ed1269f989846c8d81719fa528143",
          "md5": "44d580ade2e2d05f151adeda4af9119f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "remote-write-core-kotlin-4307936-ps17-cmp03-sources.jar",
          "url": "remote-write-core-4307936-ps17-cmp03-sources.jar",
          "size": 24582,
          "sha512": "c805ce35b772e3e92c462601a64679b67cd4e9b703c0fc85e8b9311d077bad001dd901c59f0711c143025a8e4c3d7854456f7c722dfcbc2052392283d25894ee",
          "sha256": "d7c3b5d16b84ff1230ce03237cd77f01d609c18fbe8b0f426b385e5583846814",
          "sha1": "90d0dade5d6faa3d831e15ffe2876f91b142a0a6",
          "md5": "675f5fdd22bae9380a45c4d049139100"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../remote-write-core-jvm/4307936-ps17-cmp03/remote-write-core-jvm-4307936-ps17-cmp03.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-write-core-jvm",
        "version": "4307936-ps17-cmp03"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../remote-write-core-jvm/4307936-ps17-cmp03/remote-write-core-jvm-4307936-ps17-cmp03.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-write-core-jvm",
        "version": "4307936-ps17-cmp03"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../remote-write-core-jvm/4307936-ps17-cmp03/remote-write-core-jvm-4307936-ps17-cmp03.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-write-core-jvm",
        "version": "4307936-ps17-cmp03"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../remote-write-core-wasm-js/4307936-ps17-cmp03/remote-write-core-wasm-js-4307936-ps17-cmp03.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-write-core-wasm-js",
        "version": "4307936-ps17-cmp03"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../remote-write-core-wasm-js/4307936-ps17-cmp03/remote-write-core-wasm-js-4307936-ps17-cmp03.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-write-core-wasm-js",
        "version": "4307936-ps17-cmp03"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../remote-write-core-wasm-js/4307936-ps17-cmp03/remote-write-core-wasm-js-4307936-ps17-cmp03.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-write-core-wasm-js",
        "version": "4307936-ps17-cmp03"
      }
    }
  ]
}
