{
  "formatVersion": "1.1",
  "component": {
    "url": "../../remote-write-core/4307936-ps17-cmp01/remote-write-core-4307936-ps17-cmp01.module",
    "group": "ee.schimke.remotecompose",
    "module": "remote-write-core",
    "version": "4307936-ps17-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-write-core-wasm-js-4307936-ps17-cmp01.klib",
          "url": "remote-write-core-wasm-js-4307936-ps17-cmp01.klib",
          "size": 200569,
          "sha512": "dac36ff2ec32fcd8a2da8155149e5ca461f09a9a8e43e961e93fe66239507d87cbe4876e7cce1ceda38559f3b1566a424297380df3c44ed297bcbf5469d6b582",
          "sha256": "08b269892a32d2462256c4ac5a148a9dcd8c0f3a028c086d394384da6e8a6d73",
          "sha1": "66028ef2922f3055efa165b73f7ad7f3026903df",
          "md5": "b4614941e08403093ff893fe7745b1d2"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-write-core-wasm-js-4307936-ps17-cmp01.klib",
          "url": "remote-write-core-wasm-js-4307936-ps17-cmp01.klib",
          "size": 200569,
          "sha512": "dac36ff2ec32fcd8a2da8155149e5ca461f09a9a8e43e961e93fe66239507d87cbe4876e7cce1ceda38559f3b1566a424297380df3c44ed297bcbf5469d6b582",
          "sha256": "08b269892a32d2462256c4ac5a148a9dcd8c0f3a028c086d394384da6e8a6d73",
          "sha1": "66028ef2922f3055efa165b73f7ad7f3026903df",
          "md5": "b4614941e08403093ff893fe7745b1d2"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "remote-write-core-wasm-js-4307936-ps17-cmp01-sources.jar",
          "url": "remote-write-core-wasm-js-4307936-ps17-cmp01-sources.jar",
          "size": 24450,
          "sha512": "8f1e739855f2906cca66b7c8b8c5236e03d91af760516b39bf24616f3a05e1418eaa11d1b01f490dddf9835f1d3b4337bfb6ec52099b4539ab2e6c122cb9e7b7",
          "sha256": "0eed120462df4a20f968eb41bdd0681d2889ef8de03251cf2133a623925ca947",
          "sha1": "204ef686e772e9f1a8acbd7dbaceba7cfe63c9d7",
          "md5": "c4d91f667162d2a1e0e3e7a70623678c"
        }
      ]
    }
  ]
}
