{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wear-compose-material3/1.7.0-rc01-cmp01/wear-compose-material3-1.7.0-rc01-cmp01.module",
    "group": "ee.schimke.wearcmp",
    "module": "wear-compose-material3",
    "version": "1.7.0-rc01-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-foundation",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material-core",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-material3-wasm-js-1.7.0-rc01-cmp01.klib",
          "url": "wear-compose-material3-wasm-js-1.7.0-rc01-cmp01.klib",
          "size": 2149463,
          "sha512": "bc0e5b0a99107e869915c77c0415449cd502355ee56c1c05c681275866942cc8ff129e07eaf8de0bf7af13adefc6d9f67de3aba140094db75585bb5fc849e025",
          "sha256": "c1b90dd91c90d87a282b1183c849e3b6a8541f9e85a061daadd7b3771e25d1d2",
          "sha1": "84b82e9e048c36fe1e20649eb85bffc63c320249",
          "md5": "4b49895538b1ca4693ce1633bb91aa54"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-foundation",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material-core",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-material3-wasm-js-1.7.0-rc01-cmp01.klib",
          "url": "wear-compose-material3-wasm-js-1.7.0-rc01-cmp01.klib",
          "size": 2149463,
          "sha512": "bc0e5b0a99107e869915c77c0415449cd502355ee56c1c05c681275866942cc8ff129e07eaf8de0bf7af13adefc6d9f67de3aba140094db75585bb5fc849e025",
          "sha256": "c1b90dd91c90d87a282b1183c849e3b6a8541f9e85a061daadd7b3771e25d1d2",
          "sha1": "84b82e9e048c36fe1e20649eb85bffc63c320249",
          "md5": "4b49895538b1ca4693ce1633bb91aa54"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "wear-compose-material3-wasm-js-1.7.0-rc01-cmp01-sources.jar",
          "url": "wear-compose-material3-wasm-js-1.7.0-rc01-cmp01-sources.jar",
          "size": 509070,
          "sha512": "d51b63a81f29baae7195448a7faf54082791770a6428b21307e76788328c5fcb8ddd730dafa60d24b128212e9e1e912ea2d1e8bbb9c2f927cc039edfaa788964",
          "sha256": "e77525fe26a9ff27cf2974a63e6b2c485d212ff576f52b4509b03fc25f832144",
          "sha1": "1cf71fa7393a03e09d93fe0ba64cab0690638d9f",
          "md5": "8e29d6b97bd64fd9a7bc9d10e570ef42"
        }
      ]
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-foundation",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material-core",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-material3-1.7.0-rc01-cmp01.kotlin_resources.zip",
          "url": "wear-compose-material3-wasm-js-1.7.0-rc01-cmp01-kotlin_resources.kotlin_resources.zip",
          "size": 7571,
          "sha512": "a004464f6ec38d84de7e56d4a384c1e85b00122dd6855546a2d044ce142709546f8baa441053fc106f134841fc8f9c21ab1ba723048a2aa51296b157cee97cd4",
          "sha256": "78f0a641a742f30ea897362ba4c782207c97430e42f7c0a1db7e06f211ec0ff2",
          "sha1": "621a09af14bb7e3651c6a369223731e7b32c23ea",
          "md5": "13a881305b242620653b30aebf9c9533"
        }
      ]
    }
  ]
}
