{
  "formatVersion": "1.1",
  "component": {
    "url": "../../port-runtime/1.7.0-rc01-cmp01/port-runtime-1.7.0-rc01-cmp01.module",
    "group": "ee.schimke.wearcmp",
    "module": "port-runtime",
    "version": "1.7.0-rc01-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "port-runtime-jvm-1.7.0-rc01-cmp01.jar",
          "url": "port-runtime-jvm-1.7.0-rc01-cmp01.jar",
          "size": 49117,
          "sha512": "62d9536486a78e770cca24d86f41cd0dd76860ec16310bcaa22c09c5e80ef62d2d470152ca07f36bdbe71542768c1ad7eb159d37af1a7ecaa83a41ddd8ff9643",
          "sha256": "938668a0361ebc8bfc69983e4090ded00ceffea09082abc00541b33128dc53fd",
          "sha1": "a38e948fd0cb4f6d8c1e3a2226770fd69ed96d0d",
          "md5": "eadf69df568f0b8235f4ea4c198e5979"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "port-runtime-jvm-1.7.0-rc01-cmp01.jar",
          "url": "port-runtime-jvm-1.7.0-rc01-cmp01.jar",
          "size": 49117,
          "sha512": "62d9536486a78e770cca24d86f41cd0dd76860ec16310bcaa22c09c5e80ef62d2d470152ca07f36bdbe71542768c1ad7eb159d37af1a7ecaa83a41ddd8ff9643",
          "sha256": "938668a0361ebc8bfc69983e4090ded00ceffea09082abc00541b33128dc53fd",
          "sha1": "a38e948fd0cb4f6d8c1e3a2226770fd69ed96d0d",
          "md5": "eadf69df568f0b8235f4ea4c198e5979"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "port-runtime-jvm-1.7.0-rc01-cmp01-sources.jar",
          "url": "port-runtime-jvm-1.7.0-rc01-cmp01-sources.jar",
          "size": 34362,
          "sha512": "bb9525d56db761406e10bcf5ad1b996478e8962af92de0f3b0a04de6d1383556bd5fbbfb21f4fd5c8b03a9c0e5b2f446acae6dc1f3c201ad6a3a35fd5c07ffdd",
          "sha256": "a3279063f82dc999a1b1c20306ad1b8c71e0fedf6356c29ad71d3ec24e82bedf",
          "sha1": "ba2ffb280d491e2ba4201f028812ffb7b3a782ee",
          "md5": "5a74abaae8da70b0e11e4f37dd5c9c36"
        }
      ]
    }
  ]
}
