{
  "formatVersion": "1.1",
  "component": {
    "url": "../../wear-compose-material3/1.7.0-rc01-cmp01/wear-compose-material3-1.7.0-rc01-cmp01.module",
    "group": "ee.schimke.wearcmp",
    "module": "wear-compose-material3",
    "version": "1.7.0-rc01-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-foundation",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material-core",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-material3-jvm-1.7.0-rc01-cmp01.jar",
          "url": "wear-compose-material3-jvm-1.7.0-rc01-cmp01.jar",
          "size": 2146695,
          "sha512": "9a6e2c41285299ecbf88d866db1536736e45b6c0a468d4a2050c0eaa7811253033c1870e3244f44d1e4c6e018426587be0a0e4c7b5f0b7e8b6998d2975f1111b",
          "sha256": "e940a5c2b434597accb0f566f91ebdfd5153c2640c7e96ebb3f49deb1b56c769",
          "sha1": "85c815c3bb3eb1d06aa0eb87fd9a042ec6a2720c",
          "md5": "a710fe5da4c8218462355a3d975b5a29"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-foundation",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material-core",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-material3-jvm-1.7.0-rc01-cmp01.jar",
          "url": "wear-compose-material3-jvm-1.7.0-rc01-cmp01.jar",
          "size": 2146695,
          "sha512": "9a6e2c41285299ecbf88d866db1536736e45b6c0a468d4a2050c0eaa7811253033c1870e3244f44d1e4c6e018426587be0a0e4c7b5f0b7e8b6998d2975f1111b",
          "sha256": "e940a5c2b434597accb0f566f91ebdfd5153c2640c7e96ebb3f49deb1b56c769",
          "sha1": "85c815c3bb3eb1d06aa0eb87fd9a042ec6a2720c",
          "md5": "a710fe5da4c8218462355a3d975b5a29"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "wear-compose-material3-jvm-1.7.0-rc01-cmp01-sources.jar",
          "url": "wear-compose-material3-jvm-1.7.0-rc01-cmp01-sources.jar",
          "size": 509028,
          "sha512": "103a507c7aea9eea0d020665ddff018b801e7fe2bc97a1d1cff3c2583d0ea91f7aa2a154596db20c89c426f49dbfba8c50266e13473fa187f1b385540bbf53d4",
          "sha256": "418feac5597ff7084c4c07cace18ad0d979f907bfc3b533aa8ecf7043f7f0bc0",
          "sha1": "6e2c97ca03ab98a1d3e6e8f9b9866fd2145e9346",
          "md5": "f8779c4ed38c722bb262d84cc4755f97"
        }
      ]
    }
  ]
}
