{
  "formatVersion": "1.1",
  "component": {
    "group": "ee.schimke.remotecompose",
    "module": "remote-creation-compose",
    "version": "4307936-ps17-cmp02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-write-core",
          "version": {
            "requires": "4307936-ps17-cmp02"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-creation-compose-metadata-4307936-ps17-cmp02.jar",
          "url": "remote-creation-compose-4307936-ps17-cmp02.jar",
          "size": 152469,
          "sha512": "c2c01e9d6cbc04943c172f64972cb59d81a3ddfdffbe6f139bc8014551d5d210621a14c4053b8270983b880f5117eb2d24b0bd3faa5792bf4b6a6c5a3b0c2c19",
          "sha256": "4300374b2959d73c9d86a70371750f3dcdf805910ebf2eec92839360f62beab6",
          "sha1": "d05b1bc48b8340a60dc227e8688b148399857761",
          "md5": "cccbfe0f9efa82906d4228196a9c221e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "remote-creation-compose-kotlin-4307936-ps17-cmp02-sources.jar",
          "url": "remote-creation-compose-4307936-ps17-cmp02-sources.jar",
          "size": 313904,
          "sha512": "6d797cda938202025157d9cea286881e9640af8174283633acd6c44a7cd17cb745f07bee73240d383557e2dfd5edde3c41d6799ea9cbff5fadcaa66f7c3298df",
          "sha256": "edbf9a8be6dc0d2713014882f572fef8aec9231c22fb2c85bcba38ce422e6520",
          "sha1": "b2136d2534c10f6d8ed71653ddae083e13cf9d55",
          "md5": "eaae84ed3e7c9eea8e4f9c7f3524b232"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../remote-creation-compose-android/4307936-ps17-cmp02/remote-creation-compose-android-4307936-ps17-cmp02.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-creation-compose-android",
        "version": "4307936-ps17-cmp02"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../remote-creation-compose-android/4307936-ps17-cmp02/remote-creation-compose-android-4307936-ps17-cmp02.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-creation-compose-android",
        "version": "4307936-ps17-cmp02"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../remote-creation-compose-android/4307936-ps17-cmp02/remote-creation-compose-android-4307936-ps17-cmp02.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-creation-compose-android",
        "version": "4307936-ps17-cmp02"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../remote-creation-compose-jvm/4307936-ps17-cmp02/remote-creation-compose-jvm-4307936-ps17-cmp02.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-creation-compose-jvm",
        "version": "4307936-ps17-cmp02"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../remote-creation-compose-jvm/4307936-ps17-cmp02/remote-creation-compose-jvm-4307936-ps17-cmp02.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-creation-compose-jvm",
        "version": "4307936-ps17-cmp02"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../remote-creation-compose-jvm/4307936-ps17-cmp02/remote-creation-compose-jvm-4307936-ps17-cmp02.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-creation-compose-jvm",
        "version": "4307936-ps17-cmp02"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../remote-creation-compose-wasm-js/4307936-ps17-cmp02/remote-creation-compose-wasm-js-4307936-ps17-cmp02.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-creation-compose-wasm-js",
        "version": "4307936-ps17-cmp02"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../remote-creation-compose-wasm-js/4307936-ps17-cmp02/remote-creation-compose-wasm-js-4307936-ps17-cmp02.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-creation-compose-wasm-js",
        "version": "4307936-ps17-cmp02"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../remote-creation-compose-wasm-js/4307936-ps17-cmp02/remote-creation-compose-wasm-js-4307936-ps17-cmp02.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-creation-compose-wasm-js",
        "version": "4307936-ps17-cmp02"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../remote-creation-compose-wasm-js/4307936-ps17-cmp02/remote-creation-compose-wasm-js-4307936-ps17-cmp02.module",
        "group": "ee.schimke.remotecompose",
        "module": "remote-creation-compose-wasm-js",
        "version": "4307936-ps17-cmp02"
      }
    }
  ]
}
