{
  "formatVersion": "1.1",
  "component": {
    "group": "ee.schimke.wearcmp",
    "module": "wear-compose-material3",
    "version": "1.7.0-rc01-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-foundation",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material-core",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.0-rc01-cmp01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-material3-metadata-1.7.0-rc01-cmp01.jar",
          "url": "wear-compose-material3-1.7.0-rc01-cmp01.jar",
          "size": 159810,
          "sha512": "f38e48558553d9780059345419acd5acaf0bda9d280fce40ba79e2a0d68a4bda4c0730a06aa9ee22a9494fea011cd93d5577a3c3698b556c5f0170303e074524",
          "sha256": "8a0eb204f83a3eea2601964fbcb47eb3c5b57f852c333d9d4caa105d0b7a4a2b",
          "sha1": "98aff0620dfaf80089fffee82188166986490860",
          "md5": "250767ff9759cc8bb34ff6c0708ad40f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "wear-compose-material3-kotlin-1.7.0-rc01-cmp01-sources.jar",
          "url": "wear-compose-material3-1.7.0-rc01-cmp01-sources.jar",
          "size": 507716,
          "sha512": "43a3257d030835fa6b37fa98dfccd28967dba3183b65b5bacbaef8b92ddd18831a3aaf1e89b4d5a215a6ac60d43b33bb6ddb2c8306c31db0c1de5b23bc6f1799",
          "sha256": "56d7612c4b6f0243f1580052063feccec0d577c1b1f2a1c091ee2114604b3e9a",
          "sha1": "f0a6f0fb08637b0adf82b7c999986ac154c4ac66",
          "md5": "4460288f9375a8e3c6b803b37c48b0a9"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wear-compose-material3-jvm/1.7.0-rc01-cmp01/wear-compose-material3-jvm-1.7.0-rc01-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-material3-jvm",
        "version": "1.7.0-rc01-cmp01"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wear-compose-material3-jvm/1.7.0-rc01-cmp01/wear-compose-material3-jvm-1.7.0-rc01-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-material3-jvm",
        "version": "1.7.0-rc01-cmp01"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wear-compose-material3-jvm/1.7.0-rc01-cmp01/wear-compose-material3-jvm-1.7.0-rc01-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-material3-jvm",
        "version": "1.7.0-rc01-cmp01"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wear-compose-material3-wasm-js/1.7.0-rc01-cmp01/wear-compose-material3-wasm-js-1.7.0-rc01-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-material3-wasm-js",
        "version": "1.7.0-rc01-cmp01"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wear-compose-material3-wasm-js/1.7.0-rc01-cmp01/wear-compose-material3-wasm-js-1.7.0-rc01-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-material3-wasm-js",
        "version": "1.7.0-rc01-cmp01"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wear-compose-material3-wasm-js/1.7.0-rc01-cmp01/wear-compose-material3-wasm-js-1.7.0-rc01-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-material3-wasm-js",
        "version": "1.7.0-rc01-cmp01"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wear-compose-material3-wasm-js/1.7.0-rc01-cmp01/wear-compose-material3-wasm-js-1.7.0-rc01-cmp01.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-material3-wasm-js",
        "version": "1.7.0-rc01-cmp01"
      }
    }
  ]
}
