{
  "formatVersion": "1.1",
  "component": {
    "group": "ee.schimke.wearcmp",
    "module": "wear-compose-foundation",
    "version": "1.7.1-cmp02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "port-runtime",
          "version": {
            "requires": "1.7.1-cmp02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "wear-compose-foundation-metadata-1.7.1-cmp02.jar",
          "url": "wear-compose-foundation-1.7.1-cmp02.jar",
          "size": 88859,
          "sha512": "cfb4bd1fe8df5d55ffe75dfbff95c4e048ca9a5c7258f9504ade4be904254537d1a64b3d0ced02278a1c98046e3632533497bff7cae2fd9b6f8c07deb2b18f5d",
          "sha256": "722445467e32be46b16adf0e5f41f82c2e124da65500bb4e8bda0904482d63d5",
          "sha1": "056441d38925f40cb7a8815241c65946f23fbf39",
          "md5": "ed93fe2faaa18bb7c9d8f6a01f704d06"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "wear-compose-foundation-kotlin-1.7.1-cmp02-sources.jar",
          "url": "wear-compose-foundation-1.7.1-cmp02-sources.jar",
          "size": 230759,
          "sha512": "ac2f3d9188d618b045152139c0aba52e23c4431410d5a274ceba887d4f79851441e8be420070762ba618946622444dca324f3a4bfa43104c94301df9e1ba1424",
          "sha256": "4c381b9c9f036745a4af250706dff4395fb75f5c86d1ba02aaafffa9b9dd5e98",
          "sha1": "1f51f0419be33216fae6243834a89861ce5f1b2a",
          "md5": "5085152c833f0b2d2b9ec697a3732cf0"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wear-compose-foundation-jvm/1.7.1-cmp02/wear-compose-foundation-jvm-1.7.1-cmp02.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-foundation-jvm",
        "version": "1.7.1-cmp02"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wear-compose-foundation-jvm/1.7.1-cmp02/wear-compose-foundation-jvm-1.7.1-cmp02.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-foundation-jvm",
        "version": "1.7.1-cmp02"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../wear-compose-foundation-jvm/1.7.1-cmp02/wear-compose-foundation-jvm-1.7.1-cmp02.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-foundation-jvm",
        "version": "1.7.1-cmp02"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wear-compose-foundation-wasm-js/1.7.1-cmp02/wear-compose-foundation-wasm-js-1.7.1-cmp02.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-foundation-wasm-js",
        "version": "1.7.1-cmp02"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wear-compose-foundation-wasm-js/1.7.1-cmp02/wear-compose-foundation-wasm-js-1.7.1-cmp02.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-foundation-wasm-js",
        "version": "1.7.1-cmp02"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../wear-compose-foundation-wasm-js/1.7.1-cmp02/wear-compose-foundation-wasm-js-1.7.1-cmp02.module",
        "group": "ee.schimke.wearcmp",
        "module": "wear-compose-foundation-wasm-js",
        "version": "1.7.1-cmp02"
      }
    }
  ]
}
