{
  "formatVersion": "1.1",
  "component": {
    "url": "../../remote-material3/4307936-ps17-cmp03/remote-material3-4307936-ps17-cmp03.module",
    "group": "ee.schimke.remotecompose",
    "module": "remote-material3",
    "version": "4307936-ps17-cmp03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-foundation",
          "version": {
            "requires": "4307936-ps17-cmp03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.skiko",
              "module": "*"
            }
          ]
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material3",
          "version": {
            "requires": "1.7.0-beta02-cmp09"
          },
          "excludes": [
            {
              "group": "org.jetbrains.skiko",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.skiko",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "remote-material3.aar",
          "url": "remote-material3-android-4307936-ps17-cmp03.aar",
          "size": 383917,
          "sha512": "94c24a93a5e86dd6ea70ad0d2341fb761b5c659e378a15da2ff0a2ed082e657e56ae54d757f596e7c60b51ab78fc33dc98d29eb512dad4f9c2fb7c80270d4d35",
          "sha256": "a483b2d6dde1f1a798fb45083e3204610cb9579eca3e5e3819a0cc42facadc0d",
          "sha1": "8873640b54484704972df4460130d819636fd0d2",
          "md5": "7f5d754575d031678322b8990465d2e0"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-foundation",
          "version": {
            "requires": "4307936-ps17-cmp03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.skiko",
              "module": "*"
            }
          ]
        },
        {
          "group": "ee.schimke.wearcmp",
          "module": "wear-compose-material3",
          "version": {
            "requires": "1.7.0-beta02-cmp09"
          },
          "excludes": [
            {
              "group": "org.jetbrains.skiko",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.skiko",
              "module": "*"
            }
          ]
        },
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-creation-compose",
          "version": {
            "requires": "4307936-ps17-cmp03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.skiko",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.skiko",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.skiko",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.skiko",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.12.0-alpha03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.skiko",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "remote-material3.aar",
          "url": "remote-material3-android-4307936-ps17-cmp03.aar",
          "size": 383917,
          "sha512": "94c24a93a5e86dd6ea70ad0d2341fb761b5c659e378a15da2ff0a2ed082e657e56ae54d757f596e7c60b51ab78fc33dc98d29eb512dad4f9c2fb7c80270d4d35",
          "sha256": "a483b2d6dde1f1a798fb45083e3204610cb9579eca3e5e3819a0cc42facadc0d",
          "sha1": "8873640b54484704972df4460130d819636fd0d2",
          "md5": "7f5d754575d031678322b8990465d2e0"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "remote-material3-android-4307936-ps17-cmp03-sources.jar",
          "url": "remote-material3-android-4307936-ps17-cmp03-sources.jar",
          "size": 112887,
          "sha512": "1a5411624343366f9d67eb416236625bf3eaf5c7b2b3bec2a3884ff80620ec0b648e23aa66ddc2f2d0ce865c7e0b00dd042b6def29bc111c9eb2b35e9878baff",
          "sha256": "0e2a74942821ff89335fe755b655fd8199ab40d01b1d0f2a19f23d74cf524404",
          "sha1": "e1a893ca3b94195b304e9a17c9c006fc2c53e3bb",
          "md5": "9c40f801bd04338864da070f2ed0fe9b"
        }
      ]
    }
  ]
}
