{
  "formatVersion": "1.1",
  "component": {
    "group": "ee.schimke.remotecompose",
    "module": "remote-core",
    "version": "4307936-ps17-cmp01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-core-4307936-ps17-cmp01.jar",
          "url": "remote-core-4307936-ps17-cmp01.jar",
          "size": 1553952,
          "sha512": "3c2db2647edc0bf2f114abe1dfdfacaa55ac78c640c1b4fcda2e9685a23c4a8a122e60f18cce119919b48eea30c8e49214023a2b087251017678dac957a7ff4b",
          "sha256": "582a743374b69063518d8513a37f39ab4fb4a977823e74dfc7650ecb6b66f9b2",
          "sha1": "8dd194e14d722e54a31804d49ba60a9d4629fa1b",
          "md5": "73d1c23a78bab2430cd1b43005292e1a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-core-4307936-ps17-cmp01.jar",
          "url": "remote-core-4307936-ps17-cmp01.jar",
          "size": 1553952,
          "sha512": "3c2db2647edc0bf2f114abe1dfdfacaa55ac78c640c1b4fcda2e9685a23c4a8a122e60f18cce119919b48eea30c8e49214023a2b087251017678dac957a7ff4b",
          "sha256": "582a743374b69063518d8513a37f39ab4fb4a977823e74dfc7650ecb6b66f9b2",
          "sha1": "8dd194e14d722e54a31804d49ba60a9d4629fa1b",
          "md5": "73d1c23a78bab2430cd1b43005292e1a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "remote-core-4307936-ps17-cmp01-sources.jar",
          "url": "remote-core-4307936-ps17-cmp01-sources.jar",
          "size": 856519,
          "sha512": "e4b084192e1985a24d9516bb27e35ce13676b4af822ee7506054960952a4ee385f33807af56d73fdecc895574636da900f87c40ae28dfb538f2a56cf5a8a8139",
          "sha256": "c3813859f0370f0cb7bb313ee376acb0da554bf0cab4cd580326142c84122076",
          "sha1": "993ac2e896a3133d1981b473113a3060991b04c4",
          "md5": "3a5f71c0c71f05504e717e5ea0bb5491"
        }
      ]
    }
  ]
}
