{
  "formatVersion": "1.1",
  "component": {
    "url": "../../remote-foundation/4307936-ps17-cmp04/remote-foundation-4307936-ps17-cmp04.module",
    "group": "ee.schimke.remotecompose",
    "module": "remote-foundation",
    "version": "4307936-ps17-cmp04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-creation-compose",
          "version": {
            "requires": "4307936-ps17-cmp04"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-foundation.aar",
          "url": "remote-foundation-android-4307936-ps17-cmp04.aar",
          "size": 13637,
          "sha512": "aac17efe41c3b4fe2f5b4acf7ef8d4d6af8a422c8094fcbf3a689c0e3c9910c33bd08896937d8e293904a622099eebf19192b36c202b62b4834bdfe96ef35e00",
          "sha256": "98ffd9fe0ec3962d7de231bf593b4bf56930638e83ab6539d49ce90ef4bded9f",
          "sha1": "5ac44a930aa43628dee3db53a9d6e8f3dcc04b36",
          "md5": "8bc9af06056e92a35b0ca620bd1e932d"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "ee.schimke.remotecompose",
          "module": "remote-creation-compose",
          "version": {
            "requires": "4307936-ps17-cmp04"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "remote-foundation.aar",
          "url": "remote-foundation-android-4307936-ps17-cmp04.aar",
          "size": 13637,
          "sha512": "aac17efe41c3b4fe2f5b4acf7ef8d4d6af8a422c8094fcbf3a689c0e3c9910c33bd08896937d8e293904a622099eebf19192b36c202b62b4834bdfe96ef35e00",
          "sha256": "98ffd9fe0ec3962d7de231bf593b4bf56930638e83ab6539d49ce90ef4bded9f",
          "sha1": "5ac44a930aa43628dee3db53a9d6e8f3dcc04b36",
          "md5": "8bc9af06056e92a35b0ca620bd1e932d"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "remote-foundation-android-4307936-ps17-cmp04-sources.jar",
          "url": "remote-foundation-android-4307936-ps17-cmp04-sources.jar",
          "size": 6589,
          "sha512": "d4d5b12f82aad1eced7a4eb674ab5186c9ce3193b676d0f5ad87afa21c2019e6220d175a5bd1b3e2ba0acac7a3e8a5727a76632a624d39a6cb220f58c3abf0e5",
          "sha256": "1d5c41415ff2cd3c8f6193de82ccd24a75998df3457c7a1a5846ebfd1852968b",
          "sha1": "99e982ba5cca9ab311e5c1d445a175f4375431a9",
          "md5": "d5f0900e5aac32288372fe193f338bde"
        }
      ]
    }
  ]
}
