{
  "formatVersion": "1.1",
  "component": {
    "url": "../../port-runtime/1.7.1-cmp02/port-runtime-1.7.1-cmp02.module",
    "group": "ee.schimke.wearcmp",
    "module": "port-runtime",
    "version": "1.7.1-cmp02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "port-runtime-jvm-1.7.1-cmp02.jar",
          "url": "port-runtime-jvm-1.7.1-cmp02.jar",
          "size": 49117,
          "sha512": "62d9536486a78e770cca24d86f41cd0dd76860ec16310bcaa22c09c5e80ef62d2d470152ca07f36bdbe71542768c1ad7eb159d37af1a7ecaa83a41ddd8ff9643",
          "sha256": "938668a0361ebc8bfc69983e4090ded00ceffea09082abc00541b33128dc53fd",
          "sha1": "a38e948fd0cb4f6d8c1e3a2226770fd69ed96d0d",
          "md5": "eadf69df568f0b8235f4ea4c198e5979"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.skiko",
          "module": "skiko",
          "version": {
            "requires": "0.150.1"
          }
        }
      ],
      "files": [
        {
          "name": "port-runtime-jvm-1.7.1-cmp02.jar",
          "url": "port-runtime-jvm-1.7.1-cmp02.jar",
          "size": 49117,
          "sha512": "62d9536486a78e770cca24d86f41cd0dd76860ec16310bcaa22c09c5e80ef62d2d470152ca07f36bdbe71542768c1ad7eb159d37af1a7ecaa83a41ddd8ff9643",
          "sha256": "938668a0361ebc8bfc69983e4090ded00ceffea09082abc00541b33128dc53fd",
          "sha1": "a38e948fd0cb4f6d8c1e3a2226770fd69ed96d0d",
          "md5": "eadf69df568f0b8235f4ea4c198e5979"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "port-runtime-jvm-1.7.1-cmp02-sources.jar",
          "url": "port-runtime-jvm-1.7.1-cmp02-sources.jar",
          "size": 34357,
          "sha512": "594658b364a8a1f621486aa2db155ddb12037f87037ce4bac970e3d284c40c78d94f0769f2eafbf2d48b39bae29d98ed0ca83bd26f29e598d7fefa1b3c578a95",
          "sha256": "999f31665456a4e2deb665b5297288741af9dd4bced9039a45035aecd874950d",
          "sha1": "899c04f353ab10f8e6b3cc3d43de031105e4a348",
          "md5": "2820709d205ee676fe262ea9a0668493"
        }
      ]
    }
  ]
}
